# -*- coding: utf-8 -*-
"""Day_20_Revenue_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgZcpA6qrIQfJVhaHqzvUSCwEJkH5oGt
"""

import dash
from dash import dcc, html
import plotly.express as px
import pandas as pd
import numpy as np
import seaborn as sns

# ==========================================
# 1️⃣ LOAD DATA
# ==========================================

df = sns.load_dataset("tips")

# ==========================================
# 2️⃣ DATA CLEANING
# ==========================================

df.drop_duplicates(inplace=True)
# No fillna required (tips dataset has no nulls)

# ==========================================
# 3️⃣ FEATURE ENGINEERING
# ==========================================

df["tip_pct"] = (df["tip"] / df["total_bill"]) * 100
df["revenue_per_person"] = df["total_bill"] / df["size"]

# ==========================================
# 4️⃣ KPI CALCULATIONS
# ==========================================

total_revenue = round(df["total_bill"].sum(), 2)
total_tips = round(df["tip"].sum(), 2)
avg_tip_pct = round(df["tip_pct"].mean(), 2)
avg_bill = round(df["total_bill"].mean(), 2)
avg_revenue_per_person = round(df["revenue_per_person"].mean(), 2)

peak_day = df.groupby("day")["total_bill"].sum().idxmax()
peak_time = df.groupby("time")["total_bill"].sum().idxmax()

# ==========================================
# 5️⃣ CHART DATA (AGGREGATED PROPERLY)
# ==========================================

rev_day = df.groupby("day")["total_bill"].sum().reset_index()
rev_time = df.groupby("time")["total_bill"].sum().reset_index()
rev_gender = df.groupby("sex")["total_bill"].sum().reset_index()
rev_smoker = df.groupby("smoker")["total_bill"].sum().reset_index()

# ==========================================
# 6️⃣ CHARTS
# ==========================================

rev_day_chart = px.bar(
    rev_day,
    x="day",
    y="total_bill",
    color="day",
    title="Revenue by Day"
)

rev_time_chart = px.bar(
    rev_time,
    x="time",
    y="total_bill",
    color="time",
    title="Revenue by Time"
)

tip_dist_chart = px.histogram(
    df,
    x="tip_pct",
    nbins=20,
    title="Tip % Distribution"
)

bill_tip_chart = px.scatter(
    df,
    x="total_bill",
    y="tip",
    color="time",
    size="size",
    title="Total Bill vs Tip Relationship"
)

gender_chart = px.bar(
    rev_gender,
    x="sex",
    y="total_bill",
    color="sex",
    title="Revenue by Gender"
)

smoker_chart = px.bar(
    rev_smoker,
    x="smoker",
    y="total_bill",
    color="smoker",
    title="Revenue by Smoker Status"
)

party_chart = px.box(
    df,
    x="size",
    y="total_bill",
    title="Revenue by Party Size"
)

multi_chart = px.bar(
    df,
    x="day",
    y="total_bill",
    color="time",
    barmode="group",
    title="Day & Time Revenue Comparison"
)

# ==========================================
# 7️⃣ DASH APP
# ==========================================

app = dash.Dash(__name__)

app.layout = html.Div([

    html.H1("🍽️ Restaurant Business Analytics Dashboard",
            style={"textAlign": "center"}),

    html.Br(),

    # ================= KPI SECTION =================
    html.Div([

        html.Div([
            html.H4("Total Revenue"),
            html.H2(f"${total_revenue}")
        ], style={"width": "16%", "textAlign": "center"}),

        html.Div([
            html.H4("Total Tips"),
            html.H2(f"${total_tips}")
        ], style={"width": "16%", "textAlign": "center"}),

        html.Div([
            html.H4("Average Tip %"),
            html.H2(f"{avg_tip_pct}%")
        ], style={"width": "16%", "textAlign": "center"}),

        html.Div([
            html.H4("Average Bill"),
            html.H2(f"${avg_bill}")
        ], style={"width": "16%", "textAlign": "center"}),

        html.Div([
            html.H4("Revenue / Person"),
            html.H2(f"${avg_revenue_per_person}")
        ], style={"width": "16%", "textAlign": "center"}),

        html.Div([
            html.H4("Peak Revenue Day"),
            html.H2(peak_day)
        ], style={"width": "16%", "textAlign": "center"}),

    ], style={"display": "flex", "justifyContent": "space-around"}),

    html.Hr(),

    # ================= CHARTS =================
    dcc.Graph(figure=rev_day_chart),
    dcc.Graph(figure=rev_time_chart),
    dcc.Graph(figure=tip_dist_chart),
    dcc.Graph(figure=bill_tip_chart),
    dcc.Graph(figure=gender_chart),
    dcc.Graph(figure=smoker_chart),
    dcc.Graph(figure=party_chart),
    dcc.Graph(figure=multi_chart),

])

# ==========================================
# 8️⃣ RUN
# ==========================================

if __name__ == "__main__":
    app.run(debug=True)