# -*- coding: utf-8 -*-
"""Day_17_Project_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgZcpA6qrIQfJVhaHqzvUSCwEJkH5oGt
"""

#Uber related data dashboard

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

np.random.seed(42)

dates = pd.date_range(start="2023-01-01", periods=180)

regions = ["North", "South", "East", "West"]
categories = ["Electronics", "Clothing", "Furniture"]

data = pd.DataFrame({
    "Order_Date": np.random.choice(dates, 500),
    "Region": np.random.choice(regions, 500),
    "Category": np.random.choice(categories, 500),
    "Sales": np.random.randint(1000, 10000, 500),
    "Profit": np.random.randint(100, 2000, 500)
})

data.head()

total_sales = data["Sales"].sum()
total_profit = data["Profit"].sum()
total_orders = len(data)

print("Total Sales:", total_sales)
print("Total Profit:", total_profit)
print("Total Orders:", total_orders)

monthly_sales = data.groupby(
    data["Order_Date"].dt.to_period("M")
)["Sales"].sum().reset_index()

monthly_sales["Order_Date"] = monthly_sales["Order_Date"].astype(str)

fig_line = px.line(
    monthly_sales,
    x="Order_Date",
    y="Sales",
    title="Monthly Sales Trend"
)

fig_line.show()

region_sales = data.groupby("Region")["Sales"].sum().reset_index()

fig_bar = px.bar(
    region_sales,
    x="Region",
    y="Sales",
    title="Sales by Region"
)

fig_bar.show()

category_sales = data.groupby("Category")["Sales"].sum().reset_index()

fig_pie = px.pie(
    category_sales,
    names="Category",
    values="Sales",
    title="Sales by Category"
)

fig_pie.show()

fig = make_subplots(
    rows=2, cols=2,
    specs=[[{"type": "xy"}, {"type": "xy"}],
           [{"type": "domain"}, {"type": "xy"}]],
    subplot_titles=(
        "Monthly Sales Trend",
        "Sales by Region",
        "Sales by Category",
        "Profit by Region"
    )
)

# Monthly Sales
fig.add_trace(
    go.Scatter(x=monthly_sales["Order_Date"],
               y=monthly_sales["Sales"]),
    row=1, col=1
)

# Region Sales
fig.add_trace(
    go.Bar(x=region_sales["Region"],
           y=region_sales["Sales"]),
    row=1, col=2
)

# Category Pie
fig.add_trace(
    go.Pie(labels=category_sales["Category"],
           values=category_sales["Sales"]),
    row=2, col=1
)

# Profit by Region
profit_region = data.groupby("Region")["Profit"].sum().reset_index()

fig.add_trace(
    go.Bar(x=profit_region["Region"],
           y=profit_region["Profit"]),
    row=2, col=2
)

fig.update_layout(
    height=800,
    width=1200,
    title_text="Sales Analysis Dashboard",
    template="plotly_dark",
    showlegend=False
)

fig.show()