# -*- coding: utf-8 -*-
"""Day_19_Iris_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgZcpA6qrIQfJVhaHqzvUSCwEJkH5oGt
"""

import dash
from dash import dcc, html
import plotly.express as px
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

# ===============================
# LOAD DATA
# ===============================

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["species"] = pd.Categorical.from_codes(iris.target, iris.target_names)

# Rename columns
df.columns = ["sepal_length", "sepal_width",
              "petal_length", "petal_width", "species"]

# ===============================
# KPI CALCULATIONS
# ===============================

total_records = len(df)

species_counts = df["species"].value_counts()
species_percent = (species_counts / total_records * 100).round(2)

avg_features = df.groupby("species").mean().round(2)

corr_matrix = df.drop("species", axis=1).corr().round(2)

# Outlier Detection (IQR Method)
outlier_summary = {}
for col in df.columns[:-1]:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    outliers = df[(df[col] < lower) | (df[col] > upper)]
    outlier_summary[col] = {
        "count": len(outliers),
        "percentage": round(len(outliers) / total_records * 100, 2)
    }

# ===============================
# DASH APP
# ===============================

app = dash.Dash(__name__)

# ===============================
# CHARTS
# ===============================

# Species Distribution
bar_species = px.bar(
    x=species_counts.index,
    y=species_counts.values,
    labels={"x": "Species", "y": "Count"},
    title="Species Distribution"
)

# FIXED BOX PLOT (using melt)
boxplot = px.box(
    df.melt(id_vars="species"),
    x="species",
    y="value",
    color="variable",
    title="Feature Comparison by Species",
    points="outliers"
)

# Scatter Matrix
scatter_matrix = px.scatter_matrix(
    df,
    dimensions=df.columns[:-1],
    color="species",
    title="Pair Plot (Scatter Matrix)"
)

# Correlation Heatmap
heatmap = px.imshow(
    corr_matrix,
    text_auto=True,
    color_continuous_scale="RdBu",
    title="Correlation Heatmap"
)

# ===============================
# LAYOUT
# ===============================

app.layout = html.Div([

    html.H1("🌸 Iris Dataset Analytical Dashboard",
            style={'textAlign': 'center'}),

    html.Br(),

    html.Div([
        html.Div([
            html.H3("Total Records"),
            html.H2(total_records)
        ], style={'width': '30%', 'textAlign': 'center'}),

        html.Div([
            html.H3("Species Distribution (%)"),
            html.P(str(species_percent.to_dict()))
        ], style={'width': '30%', 'textAlign': 'center'}),

        html.Div([
            html.H3("Outlier Summary"),
            html.P(str(outlier_summary))
        ], style={'width': '30%', 'textAlign': 'center'}),

    ], style={'display': 'flex', 'justifyContent': 'space-around'}),

    html.Br(),

    dcc.Graph(figure=bar_species),
    dcc.Graph(figure=boxplot),
    dcc.Graph(figure=scatter_matrix),
    dcc.Graph(figure=heatmap),

])

# ===============================
# RUN (FOR JUPYTER)
# ===============================

app.run(debug=True)