# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljJV473aMi1bZVr2IjKhOo6Hi_v33GF-
"""



import streamlit as st
import pandas as pd

st.title("Employee Salary Filter App")

# Read your uploaded CSV file
df = pd.read_csv(r"C:\Users\hp\Downloads\employees.csv")

st.subheader("All Employees Data")
st.dataframe(df)

st.divider()

# Filter employees with Salary > 50000
if "Salary" in df.columns:
    filtered_df = df[df["Salary"] > 50000]

    st.subheader("Employees with Salary > 50,000")
    st.dataframe(filtered_df)
else:
    st.error("Salary column not found in CSV file")

st.divider()

# Role Selection in Sidebar
st.sidebar.title("Select Role")

role = st.sidebar.selectbox(
    "Choose Your Role",
    ["Admin", "HR", "Employee"]
)

st.header("Role-Based Content")

if role == "Admin":
    st.success("Admin Access: You can view all employee records.")
    st.dataframe(df)

elif role == "HR":
    st.info("HR Access: You can view high salary employees only.")
    st.dataframe(filtered_df)

elif role == "Employee":
    st.warning("Employee Access: You can only view limited details.")
    st.write(df[["Name"]])