# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljJV473aMi1bZVr2IjKhOo6Hi_v33GF-
"""



import streamlit as st
import pandas as pd

st.title("CSV File Uploader")

uploaded_file = st.file_uploader("Upload a CSV file", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)

    st.success("File uploaded successfully!")
    st.write("### Data Preview")
    st.dataframe(df)
else:
    st.info("Please upload a CSV file to view its contents.")