# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljJV473aMi1bZVr2IjKhOo6Hi_v33GF-
"""



import streamlit as st

st.title("Course Selection App")

st.sidebar.title("Courses Menu")

course = st.sidebar.selectbox(
    "Select a Course",
    ["Data Science", "Full Stack Python", "Full Stack Java", "Oracle"]
)

st.write("Selected Course:", course)

if st.button("Enroll Now"):
    st.success(f"You have successfully enrolled in {course}!")