# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljJV473aMi1bZVr2IjKhOo6Hi_v33GF-
"""



import streamlit as st
import pandas as pd

st.title("Inventory Management System")

if "inventory" not in st.session_state:
    st.session_state.inventory = pd.DataFrame(
        columns=["Product Name", "Quantity", "Price"]
    )

st.sidebar.title("Menu")
menu = st.sidebar.selectbox(
    "Select Option",
    ["Add Product", "View Inventory", "Update Stock", "Delete Product"]
)

if menu == "Add Product":
    st.header("Add New Product")

    name = st.text_input("Product Name")
    quantity = st.number_input("Quantity", min_value=1, step=1)
    price = st.number_input("Price", min_value=1.0, step=1.0)

    if st.button("Add"):
        new_data = pd.DataFrame([[name, quantity, price]],
                                columns=["Product Name", "Quantity", "Price"])
        st.session_state.inventory = pd.concat(
            [st.session_state.inventory, new_data],
            ignore_index=True
        )
        st.success("Product Added Successfully")

elif menu == "View Inventory":
    st.header("Inventory List")
    st.dataframe(st.session_state.inventory)

elif menu == "Update Stock":
    st.header("Update Product Quantity")

    if not st.session_state.inventory.empty:
        product = st.selectbox(
            "Select Product",
            st.session_state.inventory["Product Name"]
        )

        new_quantity = st.number_input("New Quantity", min_value=0, step=1)

        if st.button("Update"):
            st.session_state.inventory.loc[
                st.session_state.inventory["Product Name"] == product,
                "Quantity"
            ] = new_quantity

            st.success("Stock Updated Successfully")
    else:
        st.warning("No products available")

elif menu == "Delete Product":
    st.header("Delete Product")

    if not st.session_state.inventory.empty:
        product = st.selectbox(
            "Select Product to Delete",
            st.session_state.inventory["Product Name"]
        )

        if st.button("Delete"):
            st.session_state.inventory = st.session_state.inventory[
                st.session_state.inventory["Product Name"] != product
            ]

            st.success("Product Deleted Successfully")
    else:
        st.warning("No products available")