# -*- coding: utf-8 -*-
"""Day_17_Project_04.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgZcpA6qrIQfJVhaHqzvUSCwEJkH5oGt
"""

#blinkit related data dashboard

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

np.random.seed(42)

dates = pd.date_range(start="2023-01-01", periods=90)

categories = ["Fruits", "Vegetables", "Dairy", "Snacks", "Beverages"]
cities = ["Bangalore", "Delhi", "Mumbai", "Hyderabad"]

data = pd.DataFrame({
    "Order_Date": np.random.choice(dates, 800),
    "City": np.random.choice(cities, 800),
    "Category": np.random.choice(categories, 800),
    "Order_Amount": np.random.randint(200, 3000, 800),
    "Delivery_Time_Min": np.random.randint(10, 60, 800),
    "Customer_Rating": np.random.uniform(2.5, 5.0, 800)
})

data.head()

total_orders = len(data)
total_revenue = data["Order_Amount"].sum()
avg_delivery_time = data["Delivery_Time_Min"].mean()
avg_rating = data["Customer_Rating"].mean()

print("Total Orders:", total_orders)
print("Total Revenue:", total_revenue)
print("Average Delivery Time:", round(avg_delivery_time, 2))
print("Average Rating:", round(avg_rating, 2))

daily_sales = data.groupby("Order_Date")["Order_Amount"].sum().reset_index()

fig_line = px.line(
    daily_sales,
    x="Order_Date",
    y="Order_Amount",
    title="Daily Sales Trend"
)

fig_line.show()

category_sales = data.groupby("Category")["Order_Amount"].sum().reset_index()

fig_bar = px.bar(
    category_sales,
    x="Category",
    y="Order_Amount",
    title="Sales by Category"
)

fig_bar.show()

fig_hist = px.histogram(
    data,
    x="Delivery_Time_Min",
    nbins=20,
    title="Delivery Time Distribution"
)

fig_hist.show()

rating_bins = pd.cut(
    data["Customer_Rating"],
    bins=[2.5, 3, 3.5, 4, 4.5, 5],
    labels=["2.5-3", "3-3.5", "3.5-4", "4-4.5", "4.5-5"]
)

rating_dist = rating_bins.value_counts().reset_index()
rating_dist.columns = ["Rating_Range", "Count"]

fig_pie = px.pie(
    rating_dist,
    names="Rating_Range",
    values="Count",
    title="Customer Rating Distribution"
)

fig_pie.show()

fig = make_subplots(
    rows=2, cols=2,
    specs=[[{"type": "xy"}, {"type": "xy"}],
           [{"type": "xy"}, {"type": "domain"}]],
    subplot_titles=(
        "Daily Sales Trend",
        "Category Sales",
        "Delivery Time Distribution",
        "Rating Distribution"
    )
)

# Daily Sales
fig.add_trace(
    go.Scatter(x=daily_sales["Order_Date"],
               y=daily_sales["Order_Amount"]),
    row=1, col=1
)

# Category Sales
fig.add_trace(
    go.Bar(x=category_sales["Category"],
           y=category_sales["Order_Amount"]),
    row=1, col=2
)

# Delivery Histogram
fig.add_trace(
    go.Histogram(x=data["Delivery_Time_Min"]),
    row=2, col=1
)

# Rating Pie
fig.add_trace(
    go.Pie(labels=rating_dist["Rating_Range"],
           values=rating_dist["Count"]),
    row=2, col=2
)

fig.update_layout(
    height=800,
    width=1200,
    title_text="Blinkit Sales & Delivery Dashboard",
    template="plotly_dark",
    showlegend=False
)

fig.show()