# -*- coding: utf-8 -*-
"""Day_17_Project_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgZcpA6qrIQfJVhaHqzvUSCwEJkH5oGt
"""

#Uber related data dashboard

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

np.random.seed(42)

dates = pd.date_range(start="2023-01-01", periods=30, freq="H")

locations = ["Downtown", "Airport", "Suburbs", "City Center"]
ride_types = ["UberX", "UberXL", "Uber Black"]

data = pd.DataFrame({
    "Pickup_Time": np.random.choice(dates, 1000),
    "Pickup_Location": np.random.choice(locations, 1000),
    "Ride_Type": np.random.choice(ride_types, 1000),
    "Distance_km": np.random.uniform(1, 20, 1000),
    "Fare": np.random.randint(100, 1500, 1000)
})

data["Hour"] = data["Pickup_Time"].dt.hour
data.head()

total_rides = len(data)
total_revenue = data["Fare"].sum()
avg_fare = data["Fare"].mean()

print("Total Rides:", total_rides)
print("Total Revenue:", total_revenue)
print("Average Fare:", round(avg_fare, 2))

hourly_rides = data.groupby("Hour").size().reset_index(name="Ride_Count")

fig_line = px.line(
    hourly_rides,
    x="Hour",
    y="Ride_Count",
    title="Hourly Ride Demand"
)

fig_line.show()

location_rides = data.groupby("Pickup_Location").size().reset_index(name="Ride_Count")

fig_bar = px.bar(
    location_rides,
    x="Pickup_Location",
    y="Ride_Count",
    title="Rides by Pickup Location"
)

fig_bar.show()

fig_hist = px.histogram(
    data,
    x="Fare",
    nbins=30,
    title="Fare Distribution"
)

fig_hist.show()

fig = make_subplots(
    rows=2, cols=2,
    specs=[[{"type": "xy"}, {"type": "xy"}],
           [{"type": "xy"}, {"type": "domain"}]],
    subplot_titles=(
        "Hourly Ride Demand",
        "Pickup Location Analysis",
        "Fare Distribution",
        "Ride Type Distribution"
    )
)

# Hourly Line
fig.add_trace(
    go.Scatter(x=hourly_rides["Hour"],
               y=hourly_rides["Ride_Count"]),
    row=1, col=1
)

# Location Bar
fig.add_trace(
    go.Bar(x=location_rides["Pickup_Location"],
           y=location_rides["Ride_Count"]),
    row=1, col=2
)

# Fare Histogram
fig.add_trace(
    go.Histogram(x=data["Fare"]),
    row=2, col=1
)

# Ride Type Pie
ride_type = data.groupby("Ride_Type").size().reset_index(name="Count")

fig.add_trace(
    go.Pie(labels=ride_type["Ride_Type"],
           values=ride_type["Count"]),
    row=2, col=2
)

fig.update_layout(
    height=800,
    width=1200,
    title_text="Uber Data Analysis Dashboard",
    template="plotly_dark",
    showlegend=False
)

fig.show()