# -*- coding: utf-8 -*-
"""Day_17_Project_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgZcpA6qrIQfJVhaHqzvUSCwEJkH5oGt
"""

import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Create date range
dates = pd.date_range(start="2023-01-01", periods=200)

# Create synthetic stock data
np.random.seed(42)

data = pd.DataFrame({
    "Date": dates,
    "Open": np.random.uniform(100, 200, 200),
})

data["High"] = data["Open"] + np.random.uniform(1, 10, 200)
data["Low"] = data["Open"] - np.random.uniform(1, 10, 200)
data["Close"] = data["Open"] + np.random.uniform(-5, 5, 200)
data["Volume"] = np.random.randint(1000, 10000, 200)

data.head()

fig_line = px.line(data, x="Date", y="Close",
                   title="Stock Closing Price Trend",
                   template="plotly_dark")

fig_line.show()

fig_bar = px.bar(data, x="Date", y="Volume",
                 title="Daily Trading Volume")

fig_bar.show()

fig_candle = go.Figure(data=[go.Candlestick(
    x=data["Date"],
    open=data["Open"],
    high=data["High"],
    low=data["Low"],
    close=data["Close"]
)])

fig_candle.update_layout(title="Candlestick Chart")

fig_candle.show()

fig_sub = make_subplots(rows=2, cols=1,
                        shared_xaxes=True,
                        subplot_titles=("Closing Price", "Volume"))

fig_sub.add_trace(
    go.Scatter(x=data["Date"], y=data["Close"], name="Close Price"),
    row=1, col=1
)

fig_sub.add_trace(
    go.Bar(x=data["Date"], y=data["Volume"], name="Volume"),
    row=2, col=1
)

fig_sub.update_layout(title="Stock Dashboard View")

fig_sub.show()

data["Month"] = data["Date"].dt.month
data["Year"] = data["Date"].dt.year

pivot = data.pivot_table(values="Close",
                         index="Year",
                         columns="Month",
                         aggfunc="mean")

fig_heatmap = px.imshow(pivot,
                        title="Monthly Average Closing Price Heatmap",
                        color_continuous_scale="Viridis")

fig_heatmap.show()