# -*- coding: utf-8 -*-
"""Day_19_Titanic_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fgZcpA6qrIQfJVhaHqzvUSCwEJkH5oGt
"""

import dash
from dash import dcc, html
import plotly.express as px
import pandas as pd
import seaborn as sns
import numpy as np

# ===============================
# LOAD DATA
# ===============================

df = sns.load_dataset("titanic")

# ===============================
# DATA CLEANING
# ===============================

df = df.dropna(subset=["age", "fare", "embarked"])

# Create Age Groups
df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 12, 19, 59, 100],
    labels=["Child", "Teen", "Adult", "Senior"]
)

# Create Family Size
df["family_size"] = df["sibsp"] + df["parch"] + 1

# ===============================
# KPI CALCULATIONS
# ===============================

total_passengers = len(df)
total_survivors = df["survived"].sum()
total_non_survivors = total_passengers - total_survivors
survival_rate = round((total_survivors / total_passengers) * 100, 2)

survival_by_gender = (df.groupby("sex")["survived"].mean() * 100).round(2)
survival_by_class = (df.groupby("class")["survived"].mean() * 100).round(2)
survival_by_port = (df.groupby("embarked")["survived"].mean() * 100).round(2)

# ===============================
# DASH APP
# ===============================

app = dash.Dash(__name__)

# ===============================
# CHARTS
# ===============================

# 1. Survival Distribution
pie_chart = px.pie(
    df,
    names="survived",
    title="Survival Distribution"
)

# 2. Survival by Gender
gender_bar = px.bar(
    df.groupby("sex")["survived"].mean().reset_index(),
    x="sex",
    y="survived",
    title="Survival Rate by Gender"
)

# 3. Survival by Passenger Class
class_bar = px.bar(
    df.groupby("class")["survived"].mean().reset_index(),
    x="class",
    y="survived",
    title="Survival Rate by Passenger Class"
)

# 4. Age Distribution by Survival
age_box = px.box(
    df,
    x="survived",
    y="age",
    title="Age Distribution by Survival"
)

# 5. Fare Distribution
fare_box = px.box(
    df,
    x="survived",
    y="fare",
    title="Fare Distribution by Survival"
)

# 6. Survival by Embarkation Port
port_bar = px.bar(
    df.groupby("embarked")["survived"].mean().reset_index(),
    x="embarked",
    y="survived",
    title="Survival Rate by Embarkation Port"
)

# 7. Family Size Impact
family_bar = px.bar(
    df.groupby("family_size")["survived"].mean().reset_index(),
    x="family_size",
    y="survived",
    title="Survival Rate by Family Size"
)

# ===============================
# LAYOUT
# ===============================

app.layout = html.Div([

    html.H1("🚢 Titanic Survival Analytical Dashboard",
            style={'textAlign': 'center'}),

    html.Br(),

    html.Div([
        html.Div([
            html.H3("Total Passengers"),
            html.H2(total_passengers)
        ], style={'width': '23%', 'textAlign': 'center'}),

        html.Div([
            html.H3("Total Survivors"),
            html.H2(total_survivors)
        ], style={'width': '23%', 'textAlign': 'center'}),

        html.Div([
            html.H3("Non-Survivors"),
            html.H2(total_non_survivors)
        ], style={'width': '23%', 'textAlign': 'center'}),

        html.Div([
            html.H3("Overall Survival Rate (%)"),
            html.H2(survival_rate)
        ], style={'width': '23%', 'textAlign': 'center'}),

    ], style={'display': 'flex', 'justifyContent': 'space-around'}),

    html.Br(),

    dcc.Graph(figure=pie_chart),
    dcc.Graph(figure=gender_bar),
    dcc.Graph(figure=class_bar),
    dcc.Graph(figure=age_box),
    dcc.Graph(figure=fare_box),
    dcc.Graph(figure=port_bar),
    dcc.Graph(figure=family_bar),

])

# ===============================
# RUN (FOR JUPYTER)
# ===============================

app.run(debug=True)