# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljJV473aMi1bZVr2IjKhOo6Hi_v33GF-
"""



import numpy as np

data = np.array([
    [101, 25, 5000, 1],
    [102, 30, 7000, 2],
    [103, 22, 4500, 1],
    [104, 35, 8000, 3],
    [105, 28, 6000, 2]
])

total_customers = data.shape[0]
print("Total customers:", total_customers)

purchase_column = data[:, 2]
print("Purchase amounts:", purchase_column)

average_purchase = np.mean(purchase_column)
print("Average purchase amount:", average_purchase)

max_purchase = np.max(purchase_column)
min_purchase = np.min(purchase_column)

print("Maximum purchase:", max_purchase)
print("Minimum purchase:", min_purchase)

above_average = data[purchase_column > average_purchase]
print("Customers above average purchase:\n", above_average)