# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljJV473aMi1bZVr2IjKhOo6Hi_v33GF-
"""



import numpy as np

employee_id = np.array([1, 2, 3, 4, 5])
employee_name = np.array(["Rahul", "Sneha", "Amit", "Sneha", "Kiran"])
age = np.array([25, 30, 35, 28, 40])
salary = np.array([30000, 40000, 50000, 42000, 60000])

correlation = np.corrcoef(age, salary)
print("Correlation between age and salary:\n", correlation)

mean_salary = np.mean(salary)
print("Mean salary:", mean_salary)

unique_names, counts = np.unique(employee_name, return_counts=True)
duplicates = unique_names[counts > 1]
print("Duplicate names:", duplicates)