# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljJV473aMi1bZVr2IjKhOo6Hi_v33GF-
"""



import numpy as np

production = np.array([50, 55, 48, 60, 45, 70, 52])

threshold = 50

good_quality = np.where(production >= threshold)
defective = np.where(production < threshold)

print("All production values:", production)
print("Good quality products index:", good_quality[0] + 1)
print("Defective products index:", defective[0] + 1)