# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljJV473aMi1bZVr2IjKhOo6Hi_v33GF-
"""



import numpy as np

prices = np.array([100, 200, 300, 400])

tax = 0.10

final_prices = prices + (prices * tax)

print("Original prices:", prices)
print("Final prices after tax:", final_prices)