# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljJV473aMi1bZVr2IjKhOo6Hi_v33GF-
"""



import numpy as np

sales = np.array([
    [2000, 2500, 3000, 2800],
    [1500, 1800, 2200, 2100],
    [3000, 3200, 3500, 3700]
])

total_region = np.sum(sales, axis=1)
print("Total sales per region:", total_region)

avg_month = np.mean(sales, axis=0)
print("Average sales per month:", avg_month)

best_region = np.argmax(total_region)
print("Best performing region:", best_region + 1)