# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljJV473aMi1bZVr2IjKhOo6Hi_v33GF-
"""



import numpy as np

marks = np.array([85, 72, 90, 68, 95])

sorted_marks = np.sort(marks)
print("Sorted marks:", sorted_marks)

rank_index = np.argsort(marks)[::-1]
print("Ranking (highest to lowest):", rank_index + 1)