# -*- coding: utf-8 -*-
"""Day_11_Task_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

import pandas as pd

customer_data = {
    "customer_id": [1, 2, 3, 4],
    "customer_name": ["Alice", "Bob", "Charlie", "David"],
    "city": ["Bangalore", "Mumbai", "Delhi", "Chennai"]
}

order_data = {
    "order_id": [101, 102, 103, 104, 105],
    "customer_id": [1, 2, 1, 3, 2],
    "product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer"],
    "amount": [50000, 800, 1500, 12000, 7000]
}

customers = pd.DataFrame(customer_data)
orders = pd.DataFrame(order_data)

merged_data = pd.merge(customers, orders, on="customer_id")

print(merged_data)