# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

import pandas as pd
data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "dept": ["HR", "IT", "IT", "Finance", "HR"],
    "salary": [40000, 60000, 65000, 55000, 42000]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

print("\nFiltered Data (IT Department):")
filtered_df = df[df["dept"] == "IT"]
print(filtered_df)

print("\nAverage Salary by Department:")
grouped_df = df.groupby("dept")["salary"].mean()
print(grouped_df)