# -*- coding: utf-8 -*-
"""Day_12_Task_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

import pandas as pd
#creating dataset
data = {
    "order_id": [101,102,103,104,105,101],
    "customer_id": [1,2,3,4,5,1],
    "gender": ["m","f","m","f","m","m"],
    "age": [25,30,-5,200,35,25],
    "city": ["Bangalore","Mumbai",None,"Delhi",None,"Bangalore"],
    "product category": ["electronics","Electronics","clothing","Clothing","electronics","electronics"],
    "price": [50000,2000,1500,3000,25000,50000],
    "product name": ["Laptop","Shoes","Shirt","Watch","Mobile","Laptop"],
    "quantity": [1,2,3,1,2,1],
    "order_date": ["2024-01-01","2024-01-05","2024-01-10","2024-01-15","2024-01-20","2024-01-01"]
}

df = pd.DataFrame(data)

print("Original Dataset:")
print(df)

# 1. REMOVE DUPLICATE ORDERS
df = df.drop_duplicates(subset="order_id")

print("\nAfter Removing Duplicate Orders:")
print(df)

# 2. FIX GENDER COLUMN
df["gender"] = df["gender"].replace({"m":"male","f":"female"})

print("\nAfter Fixing Gender Column:")
print(df)

# 3. HANDLE AGE ISSUES
df.loc[(df["age"] < 0) | (df["age"] > 100), "age"] = df["age"].median()

print("\nAfter Handling Age Issues:")
print(df)

# 4. FILL MISSING CITY USING MODE
df["city"] = df["city"].fillna(df["city"].mode()[0])

print("\nAfter Filling Missing City Values:")
print(df)

# 5. STANDARDIZE PRODUCT CATEGORY
df["product category"] = df["product category"].str.lower()

print("\nAfter Standardizing Product Category:")
print(df)

# 6. CONVERT ORDER DATE TO DATETIME
df["order_date"] = pd.to_datetime(df["order_date"])

print("\nAfter Converting Order Date:")
print(df)

# 7. RENAME COLUMNS TO LOWERCASE
df.columns = df.columns.str.lower()

print("\nAfter Renaming Columns to Lowercase:")
print(df)

df["revenue"] = df["price"] * df["quantity"]
# Total Revenue
total_revenue = df["revenue"].sum()
print("\nTotal Revenue:")
print(total_revenue)

# Top Cities by Sales
top_cities = df.groupby("city")["revenue"].sum().sort_values(ascending=False)
print("\nTop Cities by Sales:")
print(top_cities)

# Category Wise Sales
category_sales = df.groupby("product category")["revenue"].sum()
print("\nCategory Wise Sales:")
print(category_sales)