# -*- coding: utf-8 -*-
"""Day_11_Task_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EDkb9G7WmAH7BcTiLlE-ThaDBkGPpG24
"""

import pandas as pd

data = {
    "product_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "product_name": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer", "Tablet", "Camera", "Speaker"],
    "quantity": [10, 50, 30, 15, 8, 20, 12, 25],
    "sales": [500000, 25000, 45000, 150000, 80000, 200000, 180000, 60000]
}

df = pd.DataFrame(data)

grouped_data = df.groupby("product_name")["sales"].sum()

sorted_data = grouped_data.sort_values(ascending=False)

top5_products = sorted_data.head(5)

print(top5_products)