# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljJV473aMi1bZVr2IjKhOo6Hi_v33GF-
"""



import numpy as np

# 1. Generate 100 random temperatures between 25°C and 40°C (Uniform Distribution)
temperatures = np.random.uniform(25, 40, 100)
print("Uniform Distribution - Temperatures:\n", temperatures)


# 2. Simulate 50 student marks with mean 60 and std 10 (Normal Distribution)
student_marks = np.random.normal(60, 10, 50)
print("\nNormal Distribution - Student Marks:\n", student_marks)


# 3. Simulate 100 coin toss results (Binomial Distribution)
coin_toss = np.random.binomial(n=1, p=0.5, size=100)
print("\nBinomial Distribution - Coin Toss Results:\n", coin_toss)


# 4. Generate number of customers visiting store per hour (Poisson Distribution)
customers_per_hour = np.random.poisson(lam=20, size=24)
print("\nPoisson Distribution - Customers Per Hour:\n", customers_per_hour)


# 5. Generate 30 waiting times between customer arrivals (Exponential Distribution)
waiting_times = np.random.exponential(scale=5, size=30)
print("\nExponential Distribution - Waiting Times:\n", waiting_times)