# -*- coding: utf-8 -*-
"""Day_18_Project_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C2yQYkChjrOs6o_M85-a_UgwTpAnQV2z
"""

import dash
from dash import dcc, html
from dash.dependencies import Input, Output
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)

cities = ["Bangalore", "Delhi", "Mumbai", "Hyderabad"]
cuisines = ["North Indian", "Chinese", "Italian", "South Indian"]
ratings = np.random.uniform(2.5, 5.0, 300)
cost = np.random.randint(200, 1500, 300)

data = pd.DataFrame({
    "Restaurant_Name": [f"Restaurant_{i}" for i in range(300)],
    "City": np.random.choice(cities, 300),
    "Cuisine": np.random.choice(cuisines, 300),
    "Rating": ratings,
    "Average_Cost": cost
})

data.head()

app = dash.Dash(__name__)

app.layout = html.Div([

    html.H1("Restaurant Business Dashboard"),

    html.Label("Select City:"),
    dcc.Dropdown(
        id="city-dropdown",
        options=[{"label": c, "value": c} for c in data["City"].unique()],
        value=data["City"].unique()[0]
    ),

    dcc.Graph(id="rating-graph"),
    dcc.Graph(id="cuisine-graph")
])

@app.callback(
    [Output("rating-graph", "figure"),
     Output("cuisine-graph", "figure")],
    [Input("city-dropdown", "value")]
)
def update_dashboard(selected_city):

    filtered = data[data["City"] == selected_city]

    # Rating Distribution
    fig1 = px.histogram(
        filtered,
        x="Rating",
        title="Rating Distribution"
    )

    # Cuisine Count
    cuisine_count = filtered["Cuisine"].value_counts().reset_index()
    cuisine_count.columns = ["Cuisine", "Count"]

    fig2 = px.bar(
        cuisine_count,
        x="Cuisine",
        y="Count",
        title="Cuisine Distribution"
    )

    return fig1, fig2

if __name__ == "__main__":
    app.run(debug=True)

